name: Arduino Checks

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: submit
          compliance: strict

  compile-avr:
    name: Compile (Arduino Uno)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            - examples/Sender
            - examples/Receiver
            - examples/LowPowerSensor
            - examples/LowPowerReceiver

  compile-esp32:
    name: Compile (ESP32)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - examples/Sender
            - examples/Receiver
            - examples/LowPowerSensor
            - examples/LowPowerReceiver
            - examples/ESP32_HSPI_Sender

  compile-esp8266:
    name: Compile (ESP8266)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp8266:esp8266:nodemcuv2
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - examples/Sender
            - examples/Receiver
            - examples/LowPowerSensor
            - examples/LowPowerReceiver
